import type { Metadata, Viewport } from "next";
import { GeistSans } from "geist/font/sans";
import { GeistMono } from "geist/font/mono";
import "./globals.css";
import { cn } from "@/lib/utils";

export const metadata: Metadata = {
  title: "Farmhouse — Stanford Hacker House · Summer 2026",
  description:
    "Farmhouse is a Stanford hacker house where founders build together over the summer. Meet the founding members and their companies. Code the Farm.",
  metadataBase: new URL("https://farmhaus.vercel.app"),
  openGraph: {
    title: "Farmhouse — Stanford Hacker House · Summer 2026",
    description:
      "A Stanford hacker house where founders build together over the summer. Code the Farm.",
    type: "website",
    // OG image is generated by app/opengraph-image.tsx (file convention).
  },
  twitter: {
    card: "summary_large_image",
    title: "Farmhouse — Stanford Hacker House",
    description: "A Stanford hacker house. Code the Farm. Summer 2026.",
  },
  // favicon is served from app/icon.svg (file convention).
};

export const viewport: Viewport = {
  themeColor: "#0D0D0D",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={cn(GeistSans.variable, GeistMono.variable, "font-sans", "bg-background")}>
      <body>{children}</body>
    </html>
  );
}
